version: "3.5"

services:
  footer:
    container_name: footer
    build:
      context: ./
      dockerfile: components/footer/Dockerfile
    volumes:
      - "/usr/src/app/node_modules"
      - "./footer:/usr/src/app/"
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development

  home:
    container_name: home
    build:
      context: ./
      dockerfile: services/home/Dockerfile
    volumes:
      - ./home:/usr/src/app/
      - "/usr/src/app/node_modules"
    ports:
      - "9999:3000"
    environment:
      - NODE_ENV=development

  product:
    container_name: product
    build:
      context: ./
      dockerfile: component-spa/Dockerfile
    volumes:
      - ./product:/usr/src/app/
      - "/usr/src/app/node_modules"
    ports:
      - "9998:3001"
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    working_dir: /var/www
    ports:
      - 8080:80
